workflows:
  android-release:
    name: ScienceSpark Android Release

    environment:
      flutter: stable

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Generate launcher icons
        script: |
          dart run flutter_launcher_icons

      - name: Build APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk